/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Kaua
 */
public class Menu extends javax.swing.JDialog {

    /**
     * Creates new form Menu
     */
    public Menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        sendEmail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        searchIMG = new javax.swing.JLabel();
        redactEmailIMG = new javax.swing.JLabel();
        sendEmail = new javax.swing.JPanel();
        forEmail = new javax.swing.JTextField();
        subject = new javax.swing.JTextField();
        canselIMG = new javax.swing.JLabel();
        sendIMG = new javax.swing.JLabel();
        body = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLAsunto = new javax.swing.JLabel();
        jLPara = new javax.swing.JLabel();
        listMailJP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMail = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(950, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 410, 40));

        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("NAME");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 100, 30));

        searchIMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        jPanel1.add(searchIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, 40));

        redactEmailIMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redactEmailIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sent-mail.png"))); // NOI18N
        redactEmailIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redactEmailIMGMouseClicked(evt);
            }
        });
        jPanel1.add(redactEmailIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        sendEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forEmailActionPerformed(evt);
            }
        });
        sendEmail.add(forEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 510, -1));
        sendEmail.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 510, -1));

        canselIMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canselIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear-button.png"))); // NOI18N
        canselIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canselIMGMouseClicked(evt);
            }
        });
        sendEmail.add(canselIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 50, 50));

        sendIMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sendIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forward-arrow.png"))); // NOI18N
        sendIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendIMGMouseClicked(evt);
            }
        });
        sendEmail.add(sendIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 50, 50));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        body.setViewportView(jTextArea2);

        sendEmail.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 890, 220));

        jLAsunto.setText("Asunto:");
        sendEmail.add(jLAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 76, 50, 20));

        jLPara.setText("Para:");
        sendEmail.add(jLPara, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, 50, 20));

        jPanel1.add(sendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 920, 400));

        listMailJP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listMail.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMail);

        javax.swing.GroupLayout listMailJPLayout = new javax.swing.GroupLayout(listMailJP);
        listMailJP.setLayout(listMailJPLayout);
        listMailJPLayout.setHorizontalGroup(
            listMailJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listMailJPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        listMailJPLayout.setVerticalGroup(
            listMailJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listMailJPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(listMailJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 920, 400));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void forEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forEmailActionPerformed

    private void redactEmailIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redactEmailIMGMouseClicked
        // TODO add your handling code here:
        listMailJP.setVisible(false);
        sendEmail.setVisible(true);
    }//GEN-LAST:event_redactEmailIMGMouseClicked

    private void canselIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canselIMGMouseClicked
        // TODO add your handling code here:
        listMailJP.setVisible(true);
        sendEmail.setVisible(false);
    }//GEN-LAST:event_canselIMGMouseClicked

    private void sendIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendIMGMouseClicked
        // TODO add your handling code here:
        
        /*
            AQUI IRA EL METODO DE ENVIAR UN CORREO
        */
        
        listMailJP.setVisible(true);
        sendEmail.setVisible(false);
    }//GEN-LAST:event_sendIMGMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu dialog = new Menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane body;
    private javax.swing.JLabel canselIMG;
    private javax.swing.JTextField forEmail;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLAsunto;
    private javax.swing.JLabel jLPara;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JList<String> listMail;
    private javax.swing.JPanel listMailJP;
    private javax.swing.JLabel name;
    private javax.swing.JLabel redactEmailIMG;
    private javax.swing.JTextField search;
    private javax.swing.JLabel searchIMG;
    private javax.swing.JPanel sendEmail;
    private javax.swing.JLabel sendIMG;
    private javax.swing.JTextField subject;
    // End of variables declaration//GEN-END:variables
}
